using System.Text.Json.Serialization;

namespace Sail.Automatic1111.Models;

public record ImageToImageRequest(
    [property: JsonPropertyName("prompt")] string Prompt,
    [property: JsonPropertyName("negative_prompt")] string NegativePrompt,
    [property: JsonPropertyName("init_images")] IReadOnlyList<byte[]> InitImages,
    [property: JsonPropertyName("styles")] string[] Styles,
    [property: JsonPropertyName("seed")] int Seed,
    [property: JsonPropertyName("sampler_index")] string SamplerIndex,
    [property: JsonPropertyName("script_args")] object[] ScriptArgs,
    [property: JsonPropertyName("send_images")] bool SendImages,
    [property: JsonPropertyName("save_images")] bool SaveImages,
    [property: JsonPropertyName("resize_mode")] int ResizeMode,
    [property: JsonPropertyName("image_cfg_scale")] int ImageCfgScale,
    [property: JsonPropertyName("mask")] byte[] Mask,
    [property: JsonPropertyName("mask_blur_x")] int MaskBlurX,
    [property: JsonPropertyName("mask_blur_y")] int MaskBlurY,
    [property: JsonPropertyName("mask_blur")] int MaskBlur,
    [property: JsonPropertyName("inpainting_fill")] int InpaintingFill,
    [property: JsonPropertyName("inpaint_full_res")] bool InpaintFullResolution,
    [property: JsonPropertyName("inpaint_full_res_padding")] int InpaintFullResolutionPadding,
    [property: JsonPropertyName("inpainting_mask_invert")] int InpaintingMaskInvert,
    [property: JsonPropertyName("initial_noise_multiplier")] int InitialNoiseMultiplier,
    [property: JsonPropertyName("latent_mask")] string? LatentMask,
    [property: JsonPropertyName("include_init_images")] bool IncludeInitImages,
    [property: JsonPropertyName("alwayson_scripts")] AlwaysOnScripts AlwaysOnScripts,
    [property: JsonPropertyName("subseed")] int? Subseed = null,
    [property: JsonPropertyName("subseed_strength")] int? SubseedStrength = null,
    [property: JsonPropertyName("seed_resize_from_h")] int? SeedResizeFromH = null,
    [property: JsonPropertyName("seed_resize_from_w")] int? SeedResizeFromW = null,
    [property: JsonPropertyName("sampler_name")] string? SamplerName = null,
    [property: JsonPropertyName("batch_size")] int? BatchSize = null,
    [property: JsonPropertyName("n_iter")] int? NumberOfIterations = null,
    [property: JsonPropertyName("steps")] int? Steps = null,
    [property: JsonPropertyName("cfg_scale")] int? CfgScale = null,
    [property: JsonPropertyName("width")] int? Width = null,
    [property: JsonPropertyName("height")] int? Height = null,
    [property: JsonPropertyName("restore_faces")] bool? RestoreFaces = null,
    [property: JsonPropertyName("tiling")] bool? Tiling = null,
    [property: JsonPropertyName("do_not_save_samples")] bool? DoNotSaveSamples = null,
    [property: JsonPropertyName("do_not_save_grid")] bool? DoNotSaveGrid = null,
    [property: JsonPropertyName("eta")] int? Eta = null,
    [property: JsonPropertyName("denoising_strength")] int? DenoisingStrength = null,
    [property: JsonPropertyName("s_min_uncond")] int? SMinUncond = null,
    [property: JsonPropertyName("s_churn")] int? SChurn = null,
    [property: JsonPropertyName("s_tmax")] int? STmax = null,
    [property: JsonPropertyName("s_tmin")] int? STmin = null,
    [property: JsonPropertyName("s_noise")] int? SNoise = null,
    [property: JsonPropertyName("override_settings")] OverrideSettings? OverrideSettings = null,
    [property: JsonPropertyName("override_settings_restore_afterwards")] bool? OverrideSettingsRestoreAfterwards = null,
    [property: JsonPropertyName("refiner_checkpoint")] string? RefinerCheckpoint = null,
    [property: JsonPropertyName("refiner_switch_at")] int? RefinerSwitchAt = null,
    [property: JsonPropertyName("disable_extra_networks")] bool? DisableExtraNetworks = null,
    [property: JsonPropertyName("comments")] Comments? Comments = null,
    [property: JsonPropertyName("script_name")] string? ScriptName = null);